config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :backgrounds
  resources :songs
  resource :session
  resources :passwords, param: :token

  get "/player", to: "player#index", as: :player
  get "/player/next", to: "player#next", as: :player_next
  get "/player/background", to: "player#background", as: :player_background

  # Defines the root path route ("/")
  root "player#index"
end

app/models/background.rb
# frozen_string_literal: true

class Background < ApplicationRecord
  has_one_attached :image
end

app/controllers/backgrounds_controller.rb
# frozen_string_literal: true

class BackgroundsController < ApplicationController
  before_action :set_background, only: [ :show, :edit, :update, :destroy ]

  # GET /backgrounds or /backgrounds.json
  def index
    @backgrounds = Background.all
  end

  # GET /backgrounds/1 or /backgrounds/1.json
  def show
  end

  # GET /backgrounds/new
  def new
    @background = Background.new
  end

  # GET /backgrounds/1/edit
  def edit
  end

  # POST /backgrounds or /backgrounds.json
  def create
    params[:files].compact_blank!.each do |file|
      Background.create!(image: file)
    end

    redirect_to backgrounds_path, notice: "Backgrounds were successfully created."
  end

  # PATCH/PUT /backgrounds/1 or /backgrounds/1.json
  def update
    respond_to do |format|
      if @background.update(background_params)
        format.html { redirect_to @background, notice: "Background was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @background }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backgrounds/1 or /backgrounds/1.json
  def destroy
    @background.destroy!

    respond_to do |format|
      format.html { redirect_to backgrounds_path, notice: "Background was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_background
      @background = Background.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def background_params
      params.expect(background: [ :image ])
    end
end

app/helpers/backgrounds_helper.rb
# frozen_string_literal: true

module BackgroundsHelper
end

app/views/backgrounds/_background.html.erb
<div id="<%= dom_id background %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Image:</strong>
    <%= link_to background.image.filename, background.image, class: "text-gray-700 underline hover:no-underline" if background.image.attached? %>
  </div>
</div>

app/views/backgrounds/_form.html.erb
<%= form_with(model: background, class: "contents") do |form| %>
  <% if background.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(background.errors.count, "error") %> prohibited this background from being saved:</h2>

      <ul class="list-disc ml-6">
        <% background.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": background.errors[:image].none?, "border-red-400 focus:outline-red-600": background.errors[:image].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/backgrounds/edit.html.erb
<% content_for :title, "Editing background" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing background</h1>

  <%= render "form", background: @background %>

  <%= link_to "Show this background", @background, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to backgrounds", backgrounds_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/backgrounds/index.html.erb
<% content_for :title, "Backgrounds" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Backgrounds</h1>
    <%= link_to "New background", new_background_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="backgrounds" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @backgrounds.any? %>
      <% @backgrounds.each do |background| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render background %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", background, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_background_path(background), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", background, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No backgrounds found.</p>
    <% end %>
  </div>
</div>

app/views/backgrounds/new.html.erb
<% content_for :title, "New background" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New backgrounds</h1>

  <%= form_with(url: backgrounds_path, class: "contents") do |form| %>
    <div class="my-5">
      <%= form.label :files %>
      <%= form.file_field :files, multiple: true, required: true, class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>

  <%= link_to "Back to backgrounds", backgrounds_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/backgrounds/show.html.erb
<% content_for :title, "Showing background" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing background</h1>

  <%= render @background %>

  <%= link_to "Edit this background", edit_background_path(@background), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to backgrounds", backgrounds_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this background", @background, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>