config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :backgrounds
  resources :songs
  resource :session
  resources :passwords, param: :token

  get "/player", to: "player#index", as: :player
  get "/player/next", to: "player#next", as: :player_next
  get "/player/background", to: "player#background", as: :player_background

  # Defines the root path route ("/")
  root "player#index"
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  has_many :queued_songs, dependent: :destroy

  has_one_attached :file
  has_one_attached :cover_image

  after_create_commit :determine_metadata

  private

  def determine_metadata
    Dir.mktmpdir do |tmpdir|
      file.open(tmpdir: tmpdir) do |mp3file|
        Mp3Info.open(mp3file.path) do |mp3|
          update(
            title: mp3.tag.title.presence || "Unknown Title",
            artist: mp3.tag.artist.presence || "Unknown Artist",
            album: mp3.tag.album.presence || "Unknown Album"
          )

          if mp3.tag2.pictures.any?
            mp3.tag2.pictures.each do |name, data|
              picturepath = File.join(tmpdir, name)
              File.binwrite(picturepath, data)
              mimetype = Marcel::MimeType.for(File.open(picturepath))

              unless name.ends_with?(".jpg", ".jpeg", ".png")
                name += case mimetype
                when "image/jpeg"
                  ".jpg"
                when "image/png"
                  ".png"
                else
                  ".jpg" # Default to jpg if unknown type
                end
              end

              cover_image.attach(io: File.open(picturepath), filename: name, content_type: mimetype)
            end
          else
            cover_image.attach(io: File.open(Rails.root.join("public", "default_cover_image.png")), filename: "default_cover.jpg", content_type: "image/png")
          end
        end
      end
    end
  end
end

app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  before_action :set_song, only: [ :show, :edit, :update, :destroy ]

  def index
    @songs = Song.order(created_at: :desc)
  end

  def show
  end

  # GET /songs/new
  def new
  end

  def edit
  end

  def create
    params[:files].compact_blank!.each do |file|
      Song.create!(file: file)
    end

    redirect_to songs_path, notice: "Songs were successfully created."
  end

  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: "Song was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @song.destroy!

    respond_to do |format|
      format.html { redirect_to songs_path, notice: "Song was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  def set_song
    @song = Song.find(params.expect(:id))
  end

  def song_params
    params.expect(song: [ :title, :artist, :album, :cover_image ])
  end
end

app/helpers/songs_helper.rb
# frozen_string_literal: true

module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_with(model: song, class: "contents") do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul class="list-disc ml-6">
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": song.errors[:title].none?, "border-red-400 focus:outline-red-600": song.errors[:title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :artist %>
    <%= form.text_field :artist, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": song.errors[:artist].none?, "border-red-400 focus:outline-red-600": song.errors[:artist].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :album %>
    <%= form.text_field :album, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": song.errors[:album].none?, "border-red-400 focus:outline-red-600": song.errors[:album].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :file %>
    <%= form.file_field :file, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": song.errors[:file].none?, "border-red-400 focus:outline-red-600": song.errors[:file].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>" class="flex items-center my-5 space-x-5">
  <% if song.cover_image.attached? %>
    <%= image_tag song.cover_image.variant(resize_to_limit: [100, 100]), class: "block w-24 h-24 object-cover" %>
  <% else %>
    <div class="w-24 h-24">&nbsp;</div>
  <% end %>
  <div class="space-y-1">
    <strong class="block font-medium"><%= song.title %></strong>
    <span class="block text-gray-500"><%= song.artist %></span>
    <span class="block text-gray-500"><%= song.album %></span>
    <span class="block text-gray-500"><%= link_to song.file.filename, song.file, class: "text-gray-700 underline hover:no-underline" if song.file.attached? %></span>
  </div>
</div>

app/views/songs/edit.html.erb
<% content_for :title, "Editing song" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing song</h1>

  <%= form_with(model: @song, class: "contents") do |form| %>
    <% if @song.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
        <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

        <ul class="list-disc ml-6">
          <% song.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @song.errors[:title].none?, "border-red-400 focus:outline-red-600": @song.errors[:title].any?}] %>
    </div>

    <div class="my-5">
      <%= form.label :artist %>
      <%= form.text_field :artist, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @song.errors[:artist].none?, "border-red-400 focus:outline-red-600": @song.errors[:artist].any?}] %>
    </div>

    <div class="my-5">
      <%= form.label :album %>
      <%= form.text_field :album, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @song.errors[:album].none?, "border-red-400 focus:outline-red-600": @song.errors[:album].any?}] %>
    </div>

    <div class="my-5">
      <%= form.label :cover_image %>
      <%= form.file_field :cover_image, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @song.errors[:file].none?, "border-red-400 focus:outline-red-600": @song.errors[:file].any?}] %>
      <% if @song.cover_image.attached? %>
        <div class="mt-2">
          <%= image_tag @song.cover_image.variant(resize_to_limit: [100, 100]), class: "block w-24 h-24 object-cover" %>
        </div>
      <% end %>
    </div>

    <div class="inline">
      <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>

  <%= link_to "Show this song", @song, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to songs", songs_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/songs/index.html.erb
<% content_for :title, "Songs" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Songs</h1>
    <%= link_to "New song", new_song_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="songs" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @songs.any? %>
      <% @songs.each do |song| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render song %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", song, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_song_path(song), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", song, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No songs found.</p>
    <% end %>
  </div>
</div>

app/views/songs/new.html.erb
<% content_for :title, "New song" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New song</h1>

  <%= form_with(url: songs_path, class: "contents") do |form| %>
    <div class="my-5">
      <%= form.label :files %>
      <%= form.file_field :files, multiple: true, required: true, class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>

  <%= link_to "Back to songs", songs_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/songs/show.html.erb
<% content_for :title, "Showing song" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing song</h1>

  <%= render @song %>

  <%= link_to "Edit this song", edit_song_path(@song), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to songs", songs_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this song", @song, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>